# Generated by Django 5.0.4 on 2024-04-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physics_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Physics5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.physics_form5')),
            ],
        ),
    ]
