# Generated by Django 5.0.4 on 2024-04-18 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LECTURE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biology_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chemistry_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Economics_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='English_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Geography_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='History_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kiswahili_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mathematics_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Biology5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.biology_form5')),
            ],
        ),
        migrations.CreateModel(
            name='Chemistry5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.chemistry_form5')),
            ],
        ),
        migrations.CreateModel(
            name='Economics5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.economics_form5')),
            ],
        ),
        migrations.CreateModel(
            name='English5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.english_form5')),
            ],
        ),
        migrations.CreateModel(
            name='Geography5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.geography_form5')),
            ],
        ),
        migrations.CreateModel(
            name='History5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.history_form5')),
            ],
        ),
        migrations.CreateModel(
            name='Kiswahili5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.kiswahili_form5')),
            ],
        ),
        migrations.CreateModel(
            name='Mathematics5Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LECTURE.mathematics_form5')),
            ],
        ),
    ]
