# Generated by Django 5.0.4 on 2024-04-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTES', '0002_alter_physics_form5_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biology_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Chemistry_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Geography_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='History_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Language_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Mathematics_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='physics_form5',
            name='text',
        ),
    ]
