# Generated by Django 5.0.4 on 2024-04-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTES', '0003_biology_form5_chemistry_form5_geography_form5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economics_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='General_Studies_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Kiswahili_Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
